[workspace]
resolver = "2"
members = ["crates/ui", "crates/void", "crates/void_terminal", "crates/workspace"]
default-members = ["crates/void"]

[workspace.package]
edition = "2024"
license = "GPL-3.0-only"
publish = false

[workspace.dependencies]
anyhow = "1.0"
async-channel = "2.5"
dirs = "6.0"
gpui = { git = "https://github.com/zed-industries/zed", rev = "5e549b871fb87d1038d9b1b242bf7d4d4e3b4d8f", default-features = false }
gpui_platform = { git = "https://github.com/zed-industries/zed", rev = "5e549b871fb87d1038d9b1b242bf7d4d4e3b4d8f", default-features = false }
notify = "9.0.0-rc.4"
settings = { git = "https://github.com/zed-industries/zed", rev = "5e549b871fb87d1038d9b1b242bf7d4d4e3b4d8f" }
task = { git = "https://github.com/zed-industries/zed", rev = "5e549b871fb87d1038d9b1b242bf7d4d4e3b4d8f" }
terminal = { git = "https://github.com/zed-industries/zed", rev = "5e549b871fb87d1038d9b1b242bf7d4d4e3b4d8f" }
theme = { git = "https://github.com/zed-industries/zed", rev = "5e549b871fb87d1038d9b1b242bf7d4d4e3b4d8f" }
util = { git = "https://github.com/zed-industries/zed", rev = "5e549b871fb87d1038d9b1b242bf7d4d4e3b4d8f" }
petname = { version = "3.1.0", default-features = false, features = ["default-rng", "default-words"] }
refineable = { git = "https://github.com/zed-industries/zed", rev = "5e549b871fb87d1038d9b1b242bf7d4d4e3b4d8f" }
rust-embed = "8.12"
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
smol = "2.0"
sqlez = { git = "https://github.com/zed-industries/zed", rev = "5e549b871fb87d1038d9b1b242bf7d4d4e3b4d8f" }
sqlez_macros = { git = "https://github.com/zed-industries/zed", rev = "5e549b871fb87d1038d9b1b242bf7d4d4e3b4d8f" }
tempfile = "3.20"

[patch.crates-io]
async-process = { git = "https://github.com/zed-industries/async-process.git", rev = "0b6d6713570af61806e1e5cb40e0f757cb93fd9d" }
async-task = { git = "https://github.com/smol-rs/async-task.git", rev = "b4486cd71e4e94fbda54ce6302444de14f4d190e" }

[workspace.lints.rust]
unexpected_cfgs = { level = "allow" }

[workspace.lints.clippy]
dbg_macro = "deny"
todo = "deny"
redundant_clone = "deny"
